In [2]:
import tensorflow as tf
from tensorflow import keras
import cv2
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.layers import Activation



In [3]:

import warnings

# Ignorar todas las advertencias
warnings.filterwarnings("ignore")

In [29]:
categorias = ["Mickey","Goofy"]

matrices_numericas = []
labels = []


l = 0
numero_fotos = 7

for i in categorias:
    foto = 1
    for f in range(1,numero_fotos+1):
        img = cv2.imread( i + '/' + str(f) +".png",0)
        img = cv2.resize(img,(250,250))
        matrices_numericas.append(img)
        f = f + 1
        labels.append(l)
    l = l + 1

modelo = Sequential([
    # Primera capa convolucional
    Conv2D(64, (3, 3), activation='relu', input_shape=(250, 250, 1)),  # 64 bloques que buscan cosas importantes en la imagen
    MaxPooling2D((2, 2)),  # Reducir el tamaño del castillo para hacerlo más manejable
    
    # Segunda capa convolucional
    Conv2D(32, (3, 3), activation='relu'),  # Otros 64 bloques buscando cosas más específicas
    MaxPooling2D((2, 2)),  # Reducir el tamaño del castillo nuevamente
    
    Dropout(0.5),  # Algunos bloques toman un descanso para no volverse perezosos
    
    # Convertir el castillo en una sola línea
    Flatten(),
    
    # Nueva base del castillo con solo 2 bloques, cada uno representando una clase diferente
    Dense(2, activation='softmax')
])


# Compilar el modelo
modelo.compile(optimizer='adam',  # Usar un algoritmo especial para construir y mejorar nuestro castillo
               loss='sparse_categorical_crossentropy',  # Aprender de los errores para mejorar nuestro castillo
               metrics=['accuracy'])  # Medir qué tan bueno es nuestro castillo

matrices_numericas = np.array(matrices_numericas)
labels = np.array(labels)
modelo.fit(matrices_numericas,labels,epochs=15)

modelo.save("modeloDisney.keras")





Epoch 1/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step - accuracy: 0.5000 - loss: 26.8819
Epoch 2/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.5000 - loss: 696.8880
Epoch 3/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.5714 - loss: 23.3208
Epoch 4/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.9286 - loss: 0.4387
Epoch 5/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.7857 - loss: 16.0636
Epoch 6/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 1.0000 - loss: 5.2859e-05
Epoch 7/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.9286 - loss: 0.1217
Epoch 8/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.5714 - loss: 15.2451
Epoch 9/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 11s 11s/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 10/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 10s 10s/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 11/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 10s 10s/step - accuracy: 1.0000 - loss: 1.0218e-07
Epoch 12/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 1.0000 - loss: 0.00

In [34]:
model = tf.keras.models.load_model("modeloDisney.keras")

test=cv2.imread("test1.png",0) 
test=cv2.resize(test,(250,250)) 
test=np.asarray(test)
test=np.array([test]) 
#mikey circulos de manera abstracta para analizar

resultado=modelo.predict(test)
print(resultado)  
print("Mickey:" , resultado[0][0]*100, "%" )   
print("Goofy:" , resultado[0][1]*100 , "%" )    

print("Resultado final: " , categorias[np.argmax(resultado[0])])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
[[9.9999976e-01 2.4328534e-07]]
Mickey: 99.99997615814209 %
Goofy: 2.432853420941683e-05 %
Resultado final:  Mickey


In [32]:
model = tf.keras.models.load_model("modeloDisney.keras")

test=cv2.imread("test1.jpeg",0) 
test=cv2.resize(test,(250,250)) 
test=np.asarray(test)
test=np.array([test]) 
# Personaje a analizar es spinel de steven universe

resultado=modelo.predict(test)
print(resultado)  
print("Mickey:" , resultado[0][0]*100, "%" )   
print("Goofy:" , resultado[0][1]*100 , "%" )    

print("Resultado final: " , categorias[np.argmax(resultado[0])])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
[[1.0000000e+00 1.1716755e-17]]
Mickey: 100.0 %
Goofy: 1.171675529646252e-15 %
Resultado final:  Mickey


In [33]:
model = tf.keras.models.load_model("modeloDisney.keras")

test=cv2.imread("test2.png",0) 
test=cv2.resize(test,(250,250)) 
test=np.asarray(test)
test=np.array([test]) 

# personaje a analizar bart Simpson

resultado=modelo.predict(test)
print(resultado)  
print("Mickey:" , resultado[0][0]*100, "%" )  
print("Goofy:" , resultado[0][1]*100 , "%" )    

print("Resultado final: " , categorias[np.argmax(resultado[0])])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
[[3.5275083e-10 1.0000000e+00]]
Mickey: 3.527508285472436e-08 %
Goofy: 100.0 %
Resultado final:  Goofy
